from __future__ import annotations
from typing import Optional

"""m4_create_core_domain_models

Revision ID: 4a30adb30e8f
Revises: 241248046477
Create Date: 2026-07-30 16:35:09.185465+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '4a30adb30e8f'
down_revision: Optional[str] = '241248046477'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants')),
    sa.UniqueConstraint('slug', name=op.f('uq_tenants_slug'))
    )
    op.create_index(op.f('ix_tenants_is_active'), 'tenants', ['is_active'], unique=False)
    op.create_table('projects',
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('domain', sa.String(length=253), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], name=op.f('fk_projects_tenant_id_tenants')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_projects')),
    sa.UniqueConstraint('tenant_id', 'domain', name=op.f('uq_projects_tenant_id'))
    )
    op.create_index(op.f('ix_projects_is_active'), 'projects', ['is_active'], unique=False)
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_table('honey_tokens',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('token_type', sa.Enum('URL', 'FORM_FIELD', 'LINK', 'PIXEL', 'API_KEY', name='honeytokentype', native_enum=False, length=50), nullable=False),
    sa.Column('token_value', sa.String(length=512), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], name=op.f('fk_honey_tokens_project_id_projects')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_honey_tokens')),
    sa.UniqueConstraint('token_value', name=op.f('uq_honey_tokens_token_value'))
    )
    op.create_index(op.f('ix_honey_tokens_is_active'), 'honey_tokens', ['is_active'], unique=False)
    op.create_index(op.f('ix_honey_tokens_project_id'), 'honey_tokens', ['project_id'], unique=False)
    op.create_index(op.f('ix_honey_tokens_token_type'), 'honey_tokens', ['token_type'], unique=False)
    op.create_table('detection_events',
    sa.Column('honey_token_id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('request_path', sa.Text(), nullable=False),
    sa.Column('http_method', sa.String(length=10), nullable=False),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='eventseverity', native_enum=False, length=50), nullable=False),
    sa.Column('triggered_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['honey_token_id'], ['honey_tokens.id'], name=op.f('fk_detection_events_honey_token_id_honey_tokens')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_detection_events'))
    )
    op.create_index(op.f('ix_detection_events_honey_token_id'), 'detection_events', ['honey_token_id'], unique=False)
    op.create_index('ix_detection_events_honey_token_id_triggered_at', 'detection_events', ['honey_token_id', 'triggered_at'], unique=False)
    op.create_index(op.f('ix_detection_events_ip_address'), 'detection_events', ['ip_address'], unique=False)
    op.create_index(op.f('ix_detection_events_severity'), 'detection_events', ['severity'], unique=False)
    op.create_index(op.f('ix_detection_events_triggered_at'), 'detection_events', ['triggered_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detection_events_triggered_at'), table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_severity'), table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_ip_address'), table_name='detection_events')
    op.drop_index('ix_detection_events_honey_token_id_triggered_at', table_name='detection_events')
    op.drop_index(op.f('ix_detection_events_honey_token_id'), table_name='detection_events')
    op.drop_table('detection_events')
    op.drop_index(op.f('ix_honey_tokens_token_type'), table_name='honey_tokens')
    op.drop_index(op.f('ix_honey_tokens_project_id'), table_name='honey_tokens')
    op.drop_index(op.f('ix_honey_tokens_is_active'), table_name='honey_tokens')
    op.drop_table('honey_tokens')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_index(op.f('ix_projects_is_active'), table_name='projects')
    op.drop_table('projects')
    op.drop_index(op.f('ix_tenants_is_active'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
