from __future__ import annotations
from typing import Optional

"""expand audit log model for milestone 13

Revision ID: e13aaeedde6d
Revises: 4a30adb30e8f
Create Date: 2026-08-18 05:06:36.125122+00:00
"""

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'e13aaeedde6d'
down_revision: Optional[str] = '4a30adb30e8f'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('actor_source', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('target_entity', sa.String(length=100), nullable=True))
    op.add_column('audit_logs', sa.Column('target_id', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('tenant_id', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('project_id', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.create_foreign_key(op.f('fk_audit_logs_project_id_projects'), 'audit_logs', 'projects', ['project_id'], ['id'])
    op.create_foreign_key(op.f('fk_audit_logs_tenant_id_tenants'), 'audit_logs', 'tenants', ['tenant_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_audit_logs_tenant_id_tenants'), 'audit_logs', type_='foreignkey')
    op.drop_constraint(op.f('fk_audit_logs_project_id_projects'), 'audit_logs', type_='foreignkey')
    op.drop_column('audit_logs', 'metadata')
    op.drop_column('audit_logs', 'project_id')
    op.drop_column('audit_logs', 'tenant_id')
    op.drop_column('audit_logs', 'target_id')
    op.drop_column('audit_logs', 'target_entity')
    op.drop_column('audit_logs', 'actor_source')
    # ### end Alembic commands ###
